#!/bin/bash


if [ -z "$1" ]; then
    exit 1;
fi

BRAND_CODE=$1

JENKINS_HOME=`eval echo "~jenkins"`
JENKINS_JOBS_DIR=$JENKINS_HOME/jobs/$BRAND_CODE/builds
BUILDS_DIR=/var/www/html/$BRAND_CODE

for build in $BUILDS_DIR/jenkins*; do
    BUILD_NUM=$(echo $build | cut -d'-' -f3)
    JENKINS_BUILD_DIR=$JENKINS_JOBS_DIR/$BUILD_NUM
    ls $JENKINS_BUILD_DIR &> /dev/null
    BUILD_EXTST=$?
    if [ "$BUILD_EXTST" != 0 ]; then
        DB_NAME=`basename $build`
        rm -rf $build
        mysql-dropuser-and-db -u $DB_NAME
    fi
done
