#!/bin/bash

USAGE="$0 [-h] [-d path-to-drush] [-t [-l]] -s site-folder -o outputfile"

function _usage() {
  echo $USAGE
  cat <<EOF

This function dumps all the databases in all the site of a drupal install.
It requires drush to do the actual export.  

-d path to drush
  If drush is not in the path or a different version is to be used it can
  be set using the -d flag
-s path to the sites folder
  This is the folder holding the foder for each site.  Defaults to 
  /var/www/sites
-o oputput file
  Where the SQL dump should be saved.
-t add time stamp
-l include hours and minutesin the timestamp

EOF
}

# TIMESTAMP=0
# LONGTS=0

while getopts "hd:s:o:tl" options; do
  case $options in
    h)  _usage; exit 0;;
    d)  DRUSH="$OPTARG";;
    s)  SITE="$OPTARG";;
    o)  OUTPUT="$OUTPUT";;
    t)  TIMESTAMP=1;;
    l)  LONGTS=1;;
  esac
done

# check dependacies (drush)
if [ -z "$DRUSH" ]; then
  DRUSH=`which drush`
fi

if [ -z "$DRUSH" ]; then
  echo 'Unable to function without drush, please install it an place it in the path'
  exit 1
fi

if [ -z "$SITE" ]; then
  echo "Site to dump was not specified, cannot continue"
  exit 1
fi

# check/create dump folders
if [ ! -e "$SITE/dbdump" ]; then
  mkdir -p $SITE/dbdump
fi
if [ ! -e "$SITE/dbdump/.htaccess" ]; then
  echo "Order Deny, Allow\nDeny from all">$x/dbdump/.htaccess
fi
# dump db using drush
fname=`basename $SITE`
if [ ! -z $TIMESTAMP ]; then
  if [ ! -z $LONGTS ]; then
    dumpfile="$SITE/dbdump/auto-dump-$fname-`now`.sql"
  else
    dumpfile="$SITE/dbdump/auto-dump-$fname-`now short`.sql"
  fi
else
  dumpfile="$SITE/dbdump/auto-dump-$fname.sql"
fi
DRUPAL_PATH=`dirname $SITE`
DRUPAL_PATH=`dirname $DRUPAL_PATH`
$DRUSH -r $DRUPAL_PATH -l http://$fname sql-dump>$dumpfile

