#!/bin/bash

USAGE="$0 [-h] [-d /path/to/drush] [-s /path/to/sites/folder] /path/to/archive"

function _usage() {
  echo $USAGE
  cat <<EOF

This function dumps all the databases in all the site of a drupal install.
It requires drush to do the actual export.  

-d path to drush
  If drush is not in the path or a different version is to be used it can
  be set using the -d flag
-s sites folder
  The location of the drupal sites folder to unpack into

EOF
}

# TIMESTAMP=0
# LONGTS=0

while getopts "hd:o:" options; do
  case $options in
    h)  _usage; exit 0;;
    d)  DRUSH="$OPTARG";;
    s)  SITES="$OPTARG";;
  esac
done

shift $((OPTIND-1))
$ARCHIVE=$1

# check dependacies (drush)
if [ -z "$DRUSH" ]; then
  DRUSH=`which drush`
fi

if [ -z "$DRUSH" ]; then
  echo 'Unable to function without drush, please install it an place it in the path'
  exit 1
fi

if [ -z "$SITES" ]; then
  SITES=`pwd`
fi

# unpack the archive
# enumerate the dbdump/*.sql files
# choose sql file to restore
# restore sql
