#!/bin/bash

USAGE="$0 [-h] [-d path-to-drush] [-s sites-folder]"

function _usage() {
  echo $USAGE
  cat <<EOF

Tries to run cron on each site in a sites folder

-d path to drush
  If drush is not in the path or a different version is to be used it can
  be set using the -d flag
-s path to the sites folder
  This is the folder holding the foder for each site.  Defaults to 
  /var/www/sites

EOF
}

# TIMESTAMP=0
# LONGTS=0

while getopts "vhd:s:tl" options; do
  case $options in
    h)  _usage; exit 0;;
    d)  DRUSH="$OPTARG";;
    s)  SITES="$OPTARG";;
    v)  VERBOSE=1;;
  esac
done

# check dependacies (drush)
if [ -z "$DRUSH" ]; then
  DRUSH=`which drush`
fi

if [ -z "$DRUSH" ]; then
  echo 'Unable to function without drush, please install it an place it in the path'
  exit 1
fi

if [ -z "$SITES" ]; then
  SITES=/var/www/sites
fi

if [ $VERBOSE ]; then
  echo -e "Using drush in\n\t$DRUSH\nUsing sites folder as\n\t$SITES"
fi

# list sites and get inode nubmers of the dirs, uniq them
for x in `find $SITES -maxdepth 1 -type d -o -type l`; do
  if [ $VERBOSE ]; then echo; fi
  basename=`basename $x`
  if [ "$basename" == "all" -o "$basename" == "sites" ]; then
    # skip
    if [ $VERBOSE ]; then echo "Skip $basename"; fi
    continue
  fi
  if [ $VERBOSE ]; then echo $basename; fi
  # check for a settings.php, skip if missing
  if [ ! -e "$x/settings.php" ]; then
    if [ $VERBOSE ]; then echo " No settings file in $x, skipping"; fi
    continue
  fi
  echo $DRUSH -r `dirname $SITES` -l http://$basename cron
done

