#!/bin/bash

USAGE="$0 [-h] [-o outputfile] [-d /path/to/drush] [/path/to/site/folder]"

function _usage() {
  echo $USAGE
  cat <<EOF

This function dumps all the databases in all the site of a drupal install.
It requires drush to do the actual export.  

-d path to drush
  If drush is not in the path or a different version is to be used it can
  be set using the -d flag
-o output file
  The name of the tar/gzip bundle that will be created.  .tgz will be appended 
  to the end of the name.  By default this will be nbame of the site folder

EOF
}

# TIMESTAMP=0
# LONGTS=0

while getopts "hd:o:" options; do
  case $options in
    h)  _usage; exit 0;;
    d)  DRUSH="$OPTARG";;
    o)  OUTPUT="$OPTARG";;
  esac
done

shift $((OPTIND-1))

if [ ! -z $1 ]
then
  SITE=$1
else
  SITE=`where_am_i $0`
fi

# check dependacies (drush)
if [ -z "$DRUSH" ]; then
  DRUSH=`which drush`
fi

if [ -z "$DRUSH" ]; then
  echo 'Unable to function without drush, please install it an place it in the path'
  exit 1
fi

SITENAME=`basename $SITE`

if [ -z "$OUTPUT" ]; then
  OUTPUT=$SITENAME
fi
OUTPUT="$OUTPUT.tgz"

SETTINGS=$SITE/settings.php
if [ ! -e "$SETTINGS" ]; then
  echo 'The site you specified does not seem to have a valid settings file in it.'
  exit 1
fi

echo "Using drush in     $DRUSH"
echo "Site path set to   $SITE"
echo "Site name set to   $SITENAME"
echo "Output file set to $OUTPUT"

`dirname $0`/drupal-db-dump -t -l -s $SITE

tar -C `dirname $SITE` -zcf $OUTPUT `basename $SITE`
