#!/bin/bash

USAGE="$0 <drupalroot>"

# TODO - getopts and help output
# TODO - make it work on non debian systems
if [ -z $1 ]; then
  DR=/var/www
else
  DR=$1
fi

_USER=$SUDO_USER

if [ -z "$_USER" ]; then
    echo "You must run this script using sudo"
    exit 1
fi

echo $DR
if [ -z "$DR" ]; then
    echo "Usage: $0 path_to_drupal_site_root"
    exit 2
fi

if [ ! -d "$DR" ]; then
    echo "Drupal dir doesnot exist"
    echo $USEAGE
    exit 3
fi

FILEDIR="$DR/files"
if [ ! -d "FILEDIR" ]; then
  FILEDIR="$DR/sites/*/files"
fi

chown -R $SUDO_UID:users $DR
chown -R www-data:www-data $FILEDIR
find $FILEDIR -name .svn -exec chown $SUDO_UID:www-data {} \;
find $FILEDIR -type d -exec chmod 1775 {} \;
find $FILEDIR -type f -exec chmod 664 {} \;
