#!/bin/bash

NO_ARGS=0
USAGE="$0 CURTAG NEWTAG"
if [ $# -eq "$NO_ARGS" ]; then
    echo $USAGE
    exit 1
fi

CUR_TAG=$1
NEW_TAG=$2

if [ -z "$CUR_TAG" ] || [ -z "$NEW_TAG" ]; then
    echo $USAGE
    exit 1
fi

echo $NEW_TAG > newchangelog.txt
echo "======" >> newchangelog.txt
git log --no-merges --format="%ai %aN %b %n%n%x09* %s%d%n" $CUR_TAG..master >> newchangelog.txt
cat changelog.txt >> newchangelog.txt
mv newchangelog.txt changelog.txt
git commit -a -m 'Updated change log'
git tag $NEW_TAG
git push origin master --tags
