#!/bin/bash

source /usr/local/bin/colours
USAGE="ghib <repo url> [issue number]"
STORAGE=$HOME/.tobybatch/ghib

which ghi > /dev/null
if [ "$?" != 0 ]; then
  echo "$0 depends on ghi, https://github.com/tobybatch/ghi"
  echo "sudo gem install ghi"
fi

if [ ! -z "$1" ]; then
  mkdir -p $HOME/.tobybatch
  echo $1 > $STORAGE
  REPO=$1
fi

if [ -z "$REPO" ]; then
  if [ -e "$STORAGE" ]; then
    REPO=`cat $STORAGE`
  else
    echo $USAGE
    exit 1;
  fi
fi

if [ ! -z "$2" ]; then
  ISSUE_NUM=$2;
fi

if [ -z "$ISSUE_NUM" ]; then
  ISSUE_LIST="$(ghi list $1)"
  echo "${ISSUE_LIST}"
  echo
  echo -e $COL_GREEN"Choose issue number"$COL_RESET
  read ISSUE_NUM
fi

TITLE="$(ghi show $ISSUE_NUM $1 | head -n1)"
echo -e $COL_YELLOW"Title: $TITLE"$COL_RESET
CLEAN=${TITLE,,}
CLEAN=${CLEAN//[^a-zA-Z0-9 ]/}
CLEAN=$(echo $CLEAN | sed 's/ /_/g')
echo -e $COL_YELLOW"Sanitized title: $CLEAN"$COL_RESET

EXISTS=$(git show-ref refs/heads/$CLEAN)
if [ -n "$EXISTS" ]; then
  echo 'Branch exists'
  exit 0
fi

echo -e $COL_GREEN"Creating a branch named $CLEAN from develop (y/n)"$COL_RESET
read a
if [ "$a" == 'y' ] || [ "$a" == 'Y']; then
  git checkout develop
  git checkout -b $CLEAN
fi

