#!/bin/bash

NO_ARGS=0
USAGE="`basename $0` ip outputdir"

function usage {
    echo $USAGE
    cat <<EOF

Fires a single ping to the destination ip specified and writes a log output to
the specified folder.  The output is stored in files named on the reverse of 
todays date, year, month, day of month.  Each attempt os recorded in a file named
'DATE'.log and any failed attempts in 'DATE'.err.

  ip
    The address to ping

  outputdir
    The directory to write the log file(s) to.
EOF
}

if [ $# -eq "$NO_ARGS" ]  # Script invoked with no command-line args?
then
    usage
    exit 3
fi

HEART=$1
RESULTS=$2

if [ -z "$HEART" ] || [ -z "$RESULTS" ]; then
    echo Insufficient paramters. Unable to proceed
    echo
    usage
    exit 4
fi

if [ ! -d "$RESULTS" ]; then
    echo $RESULTS does not exist.  Exiting cowardly.
    exit 1
fi

LOG=$RESULTS/`date +"%Y_%m_%d"`.log
ERR=$RESULTS/`date +"%Y_%m_%d"`.err

touch $LOG
if [ "$?" != 0 ]; then
    echo "Could not create/write to log file: $LOG. Check permissions."
    exit 2
fi

touch $ERR
if [ "$?" != 0 ]; then
    echo "Could not create/write to err file: $ERR Check permissions."
    exit 2
fi

ping -c1 $HEART > /dev/null

if [ "$?" != 0 ]; then
    echo `date` >> $ERR
fi

echo `date` >> $LOG
