#!/bin/bash

CWD=`dirname $0`
source $CWD/colours

# Theme path
THEME_PATH=$1

if [ -z "$THEME_PATH" ]; then
    THEME_PATH=`pwd`
fi

for x in $THEME_PATH/*; do
    if [ -d "$x" ]; then
        echo -e "${COL_GREEN}Compass compile ${x}${COL_RESET}"
        compass compile $x
    else
        echo -e "${COL_YELLOW}Not a theme: ${x}${COL_RESET}"
    fi
done
