#!/bin/bash

USAGE="$(basename "$0") [-s] [-x]"

source "$(dirname "$0")/colours"

function usage() {
  echo $USAGE
  cat <<EOF

Generates a randon 24 character password.  The -s flag restricts the password
to alphanumeric characters only.  The -x will use the XKCD random four word
password generation (http://xkcd.com/936/)

EOF
  exit
}

source "$(dirname "$0")"/colours

while getopts "hsx" options; do
  case $options in
    h)  usage;;
    x)  xkcd=1;;
    s)  safe=1;;
    *)  echo "Unknown option";;
  esac
done

if [ -z $xkcd ]; then
  if [ -z $safe ]; then
    pass=$(</dev/urandom tr -dc 'A-Za-z0-9!@#$%&/()=' | head -c24)
  else
    pass=$(</dev/urandom tr -dc 'A-Za-z0-9' | head -c24)
  fi
else
  pass=$( \
    grep -v "'" /usr/share/dict/words| \
    shuf -n4 | \
    sed 's/.*/\L&/g' | \
    iconv -f utf8 -t ascii//TRANSLIT \
    )
fi

colours="$COL_RED $COL_GREEN $COL_YELLOW $COL_BLUE"

for word in $pass; do
  colour=$(echo "$colours" | awk '{print $1}')
  echo -en "$colour""$word"
  colours=$(echo "$colours" | awk '{$1="";print $0}')
done
echo -e "$COL_RESET"

echo "$pass" | tr -d '\n' | xsel -ib

if [ "$?" ]; then
  echo "The password has been pushed to your clipboard, you can paste it where you want it"
fi
