#!/bin/bash

set -e
set -x

# 20150219161426-01.jpg
# 20130501091550_57.jpg

ORIGIMG="/tmp/foo/95-20150219161426-01.jpg"
# ORIGIMG="/tmp/foo/000DC5D252CC()_0_20130501091550_57.jpg"
ROOT='/var/tmp/cam01'

ORIGIMG=`echo $ORIGIMG | sed -e "s/-/_/g"`

IFS='_' read -a parts <<< "$ORIGIMG"

IMG=${parts[2]}_${parts[3]}
# IMG="$( cut -d '_' -f 3,4 <<< "$ORIGIMG" )"
YEAR="$( cut -c 1,2,3,4 <<< "$IMG" )"
MONTH="$( cut -c 5,6 <<< "$IMG" )"
DAY="$( cut -c 7,8 <<< "$IMG" )"
HOUR="$( cut -c 9,10 <<< "$IMG" )"
MINUTE="$( cut -c 11,12 <<< "$IMG" )"
SECOND="$( cut -c 13,14 <<< "$IMG" )"
NAME="$( cut -c 16,17,18,19,20,21 <<< "$IMG" )"
DIR="$YEAR/$MONTH/$DAY/$HOUR/$MINUTE"
FILE="$YEAR-$MONTH-$DAY-$HOUR:$MINUTE:$SECOND-$NAME"

echo mkdir -p $DIR
echo mv "$ORIGIMG" $ROOT/$DIR/$FILE
