#!/bin/bash

#!/bin/bash

USAGE="$0 <drupalroot>"

# TODO - getopts and help output
# TODO - make it work on non debian systems
if [ -z $1 ]; then
  DR=/var/www
else
  DR=$1
fi

_USER=$SUDO_USER

if [ -z "$_USER" ]; then
    echo "You must run this script using sudo"
    exit 1
fi

echo $DR
if [ -z "$DR" ]; then
    echo "Usage: $0 path_to_drupal_site_root"
    exit 2
fi

if [ ! -d "$DR" ]; then
    echo "Drupal dir doesnot exist"
    echo $USEAGE
    exit 3
fi

SITESDIR="$DR/sites"

PS3="Choose site to clear:"
select name in $SITESDIR/*
do 
  break
done

if [ ! -z "$name" ]; then
  /usr/local/drush/drush -r $DR -l http://`basename $name` cc all
fi
